### ISSUE TITLE
Add Percentage Progress while downloading file

### ISSUE THREAD

**Issue by fikimaul** [fikimaul/fikfile-downloader#1]
Adding Percentage Progress while downloading file Like when npm install :D

**Comment by Shivank-Dev** [comment]
Hi, I'm interested in this. how can I get started?

**Comment by fikimaul** [comment]
@Shivank-Dev  just fork and add loading like this 

![image](https://user-images.githubusercontent.com/18456011/95161082-668a6200-07cc-11eb-877b-7429f55c3d6f.png)

**Comment by Shivank-Dev** [comment]
Okay, thanks :)

**Comment by Shivank-Dev** [comment]
hey @fikimaul,  I have created one PR related this issue could u please look into this

**Comment by fikimaul** [comment]
Hi @Shivank-Dev thnks for your work. 💯
